# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3Up7aLSQWzkXtde-THhdNbY4fyq-UGh
"""

import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"  # suppress TensorFlow C++ log spam

import matplotlib
matplotlib.use("Agg")  # headless / non-interactive backend, we only save PNGs
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
from scipy.optimize import minimize
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor,
    BaggingRegressor,
)
from sklearn.neural_network import MLPRegressor
from sklearn.base import clone
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import warnings

warnings.filterwarnings("ignore")
tf.get_logger().setLevel("ERROR")
tf.random.set_seed(42)

print("=" * 90)
print("STREAMFLOW PREDICTION - CHRONOLOGICAL TRAIN/VAL/TEST + 2-MODEL REGIME-BMA")
print("=" * 90)

# ===========================================================================
# ==================== STEP 1: DATA CLEANING & TABULAR FEATURE PREPARATION ====================
# ===========================================================================

def nse(y_true, y_pred):
    """Nash-Sutcliffe Efficiency."""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    numerator = np.sum((y_true - y_pred) ** 2)
    denominator = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (numerator / denominator)


def kge(y_true, y_pred):
    """Kling-Gupta Efficiency (Gupta et al., 2009)."""
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    r = np.corrcoef(y_true, y_pred)[0, 1]
    alpha = np.std(y_pred) / np.std(y_true)   # variability ratio
    beta = np.mean(y_pred) / np.mean(y_true)  # bias ratio

    return 1 - np.sqrt((r - 1) ** 2 + (alpha - 1) ** 2 + (beta - 1) ** 2)

# Raw input data are not included in this repository.
df = pd.read_csv("data/West Rapti_input for ML.csv")
print(f"\nDataset shape: {df.shape}")

df["Date"] = pd.to_datetime(df["Date"], format="%Y %m %d")
df = df.sort_values("Date").reset_index(drop=True)  # enforce chronological order

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfYear"] = df["Date"].dt.dayofyear
df["Month_sin"] = np.sin(2 * np.pi * df["Month"] / 12)
df["Month_cos"] = np.cos(2 * np.pi * df["Month"] / 12)
df["DayOfYear_sin"] = np.sin(2 * np.pi * df["DayOfYear"] / 365)
df["DayOfYear_cos"] = np.cos(2 * np.pi * df["DayOfYear"] / 365)

df["is_monsoon"] = df["Month"].isin([6, 7, 8, 9]).astype(int)

seasonal_features = ["Month_sin", "Month_cos", "DayOfYear_sin", "DayOfYear_cos"]

df["precip_sum_3d"] = df["IMERG_prep(mm/day)"].rolling(window=3).sum()
df["precip_sum_7d"] = df["IMERG_prep(mm/day)"].rolling(window=7).sum()
df["precip_sum_14d"] = df["IMERG_prep(mm/day)"].rolling(window=14).sum()

df["Tavg_roll_mean_3d"] = df["Tavg"].rolling(window=3).mean()
df["Tavg_roll_mean_7d"] = df["Tavg"].rolling(window=7).mean()
df["Tavg_roll_mean_14d"] = df["Tavg"].rolling(window=14).mean()

df["PET_roll_mean_3d"] = df["PET"].rolling(window=3).mean()
df["PET_roll_mean_7d"] = df["PET"].rolling(window=7).mean()
df["PET_roll_mean_14d"] = df["PET"].rolling(window=14).mean()

df["precip_gradient"] = df["IMERG_prep(mm/day)"] - df["IMERG_prep(mm/day)"].shift(1)

base_features = [
    "IMERG_prep(mm/day)", "Tavg", "PET",
    "precip_sum_3d", "precip_sum_7d", "precip_sum_14d",
    "Tavg_roll_mean_3d", "Tavg_roll_mean_7d", "Tavg_roll_mean_14d",
    "PET_roll_mean_3d", "PET_roll_mean_7d", "PET_roll_mean_14d",
    "precip_gradient", "is_monsoon",
]

features = base_features + seasonal_features

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"Dataset shape after dropping NaNs from rolling-window construction: {df.shape}")
print(f"Feature set ({len(features)} features): {features}")

y_all = df["streamflow"].values
X_all = df[features].values
is_monsoon_all = df["is_monsoon"].values

# ===========================================================================
# ==================== STEP 2: CHRONOLOGICAL SEPARATION OF UNTOUCHED TEST SET (2017-2019) ====================
# ===========================================================================

TRAINVAL_POOL_END_DATE = pd.Timestamp("2016-12-31")

pool_mask = df["Date"] <= TRAINVAL_POOL_END_DATE
test_mask = df["Date"] > TRAINVAL_POOL_END_DATE

pool_idx = np.where(pool_mask)[0]
test_idx = np.where(test_mask)[0]

X_pool, y_pool, is_monsoon_pool = X_all[pool_idx], y_all[pool_idx], is_monsoon_all[pool_idx]
X_test, y_test, is_monsoon_test = X_all[test_idx], y_all[test_idx], is_monsoon_all[test_idx]

print(f"Pool (2003-2016): {len(pool_idx)} rows "
      f"({df['Date'].iloc[pool_idx[0]].date()} to {df['Date'].iloc[pool_idx[-1]].date()})")
print(f"Test (2017-2019): {len(test_idx)} rows "
      f"({df['Date'].iloc[test_idx[0]].date()} to {df['Date'].iloc[test_idx[-1]].date()})")

FIRST_VAL_YEAR = 2009
LAST_VAL_YEAR = 2016

expanding_window_folds = []
print(f"\nExpanding-window validation folds within the pool (calendar-year expanding window, "
      f"validating {FIRST_VAL_YEAR}-{LAST_VAL_YEAR}):")
for fold_num, val_year in enumerate(range(FIRST_VAL_YEAR, LAST_VAL_YEAR + 1), start=1):
    fold_train_mask = (df["Date"] <= TRAINVAL_POOL_END_DATE) & (df["Year"] < val_year)
    fold_val_mask = df["Year"] == val_year

    fold_train_idx = np.where(fold_train_mask)[0]
    fold_val_idx = np.where(fold_val_mask)[0]

    expanding_window_folds.append({
        "fold": fold_num,
        "train_idx": fold_train_idx,
        "val_idx": fold_val_idx,
    })

    print(f"  Fold {fold_num}: train {len(fold_train_idx):>5} rows "
          f"({df['Date'].iloc[fold_train_idx[0]].date()} to "
          f"{df['Date'].iloc[fold_train_idx[-1]].date()})  ->  "
          f"val {len(fold_val_idx):>5} rows "
          f"({df['Date'].iloc[fold_val_idx[0]].date()} to "
          f"{df['Date'].iloc[fold_val_idx[-1]].date()})")

print(f"\nStored {len(expanding_window_folds)} expanding-window fold(s) in "
      f"`expanding_window_folds` for reuse in later steps.")

# ===========================================================================
# ==================== STEP 3: BASE LEARNER ARCHITECTURE TEMPLATES ====================
# ===========================================================================

def build_models():
    return {
        "Linear Regression": LinearRegression(),
        "Ridge": Ridge(alpha=1.0),
        "Lasso": Lasso(alpha=0.1, max_iter=10000),
        "ElasticNet": ElasticNet(alpha=0.1, l1_ratio=0.5, max_iter=10000),
        "Decision Tree": DecisionTreeRegressor(random_state=42, max_depth=15),
        "Random Forest": RandomForestRegressor(
            n_estimators=200, random_state=42, max_depth=20, n_jobs=-1
        ),
        "Extra Trees": ExtraTreesRegressor(
            n_estimators=200, random_state=42, max_depth=20, n_jobs=-1
        ),
        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=300, random_state=42, max_depth=6,
            learning_rate=0.1, subsample=0.8,
        ),
        "Bagging": BaggingRegressor(
            n_estimators=200, random_state=42, n_jobs=-1
        ),
        "MLP": MLPRegressor(
            hidden_layer_sizes=(128, 64, 32),
            max_iter=500, random_state=42,
            early_stopping=True, learning_rate="adaptive",
        ),
        "XGBoost": XGBRegressor(
            n_estimators=300, learning_rate=0.05, max_depth=6,
            subsample=0.8, colsample_bytree=0.8,
            random_state=42, n_jobs=-1, verbosity=0,
        ),
        "LightGBM": LGBMRegressor(
            n_estimators=300, learning_rate=0.05, max_depth=6,
            subsample=0.8, colsample_bytree=0.8,
            random_state=42, n_jobs=-1, verbose=-1,
        ),
        "LSTM": None,
    }


def build_lstm(n_features):
    """Small LSTM sized to the fixed feature count."""
    model = Sequential([
        Input(shape=(1, n_features)),
        LSTM(64, activation="tanh", return_sequences=False),
        Dropout(0.2),
        Dense(32, activation="relu"),
        Dense(1),
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss="mse")
    return model


LSTM_SEED = 42  # single fixed seed


def _train_lstm_predict(X_tr_scaled, y_tr, X_predict_scaled, seed=LSTM_SEED):
    """Train a single LSTM on (X_tr_scaled, y_tr) with a fixed seed, then
    predict X_predict_scaled. Called once for Phase 1 (Train -> Val) and once
    for Phase 2 (Train+Val -> Test) - each call is a fresh refit."""
    n_feat = X_tr_scaled.shape[1]
    X_tr_lstm = X_tr_scaled.reshape((X_tr_scaled.shape[0], 1, n_feat))
    X_pred_lstm = X_predict_scaled.reshape((X_predict_scaled.shape[0], 1, n_feat))

    tf.random.set_seed(seed)
    np.random.seed(seed)

    lstm = build_lstm(n_feat)
    early_stop = EarlyStopping(
        monitor="val_loss", patience=8, restore_best_weights=True
    )
    lstm.fit(
        X_tr_lstm, y_tr,
        validation_split=0.15,
        epochs=50,
        batch_size=32,
        callbacks=[early_stop],
        verbose=0,
    )
    return lstm.predict(X_pred_lstm, verbose=0).flatten()


def _metrics_row(label, y_true, y_pred, prefix="Test"):
    return {
        "Model": label,
        f"{prefix}_R2": r2_score(y_true, y_pred),
        f"{prefix}_NSE": nse(y_true, y_pred),
        f"{prefix}_KGE": kge(y_true, y_pred),
        f"{prefix}_RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        f"{prefix}_MAE": mean_absolute_error(y_true, y_pred),
    }


def _tie_breaker_rank(rows_df, kge_col, nse_col, r2_col, mae_col, rmse_col):
    """Tie-breaker sort: rounded KGE > rounded NSE > rounded R2 > MAE > RMSE."""
    ranking = rows_df.copy()
    ranking["_KGE_r"] = ranking[kge_col].round(2)
    ranking["_NSE_r"] = ranking[nse_col].round(2)
    ranking["_R2_r"] = ranking[r2_col].round(2)
    ranked = ranking.sort_values(
        by=["_KGE_r", "_NSE_r", "_R2_r", mae_col, rmse_col],
        ascending=[False, False, False, True, True],
    ).drop(columns=["_KGE_r", "_NSE_r", "_R2_r"]).reset_index(drop=True)
    return ranked


pd.set_option("display.max_rows", None)
pd.set_option("display.width", 160)

# ===========================================================================
# ==================== STEP 4, PART 1: EXPANDING-WINDOW OOF GENERATION & POOLED-OOF MODEL SELECTION ====================
# ===========================================================================
print("\n" + "=" * 90)
print("STEP 4 PART 1: EXPANDING-WINDOW BASE LEARNER TRAINING AND POOLED-OOF MODEL SELECTION")
print("            (TRAINING/MODEL-SELECTION POOL ONLY, 2003-2016; TEST SET UNTOUCHED)")
print("=" * 90)

phase1_templates = build_models()
ALL_CANDIDATES = tuple(name for name in phase1_templates if name != "LSTM") + ("LSTM",)

MODEL_FAMILIES = {
    "Linear Regression": "linear",
    "Ridge": "linear",
    "Lasso": "linear",
    "ElasticNet": "linear",
    "Decision Tree": "tree",
    "Random Forest": "tree",
    "Extra Trees": "tree",
    "Gradient Boosting": "tree",
    "Bagging": "tree",
    "XGBoost": "tree",
    "LightGBM": "tree",
    "MLP": "neural",
    "LSTM": "neural",
}

n_pool = len(pool_idx)
pool_position = {abs_idx: pos for pos, abs_idx in enumerate(pool_idx)}

oof_predictions = {name: np.full(n_pool, np.nan) for name in ALL_CANDIDATES}

fold_records = []
fold_metric_rows = []

for fold_info in expanding_window_folds:
    fold_num = fold_info["fold"]
    fold_train_idx = fold_info["train_idx"]
    fold_val_idx = fold_info["val_idx"]

    X_fold_train, y_fold_train = X_all[fold_train_idx], y_all[fold_train_idx]
    X_fold_val, y_fold_val = X_all[fold_val_idx], y_all[fold_val_idx]
    is_monsoon_fold_val = is_monsoon_all[fold_val_idx]

    fold_scaler = StandardScaler()
    X_fold_train_sc = fold_scaler.fit_transform(X_fold_train)
    X_fold_val_sc = fold_scaler.transform(X_fold_val)

    print(f"\nFold {fold_num}: train {len(fold_train_idx):>5} rows "
          f"({df['Date'].iloc[fold_train_idx[0]].date()} to "
          f"{df['Date'].iloc[fold_train_idx[-1]].date()})  ->  "
          f"val {len(fold_val_idx):>5} rows "
          f"({df['Date'].iloc[fold_val_idx[0]].date()} to "
          f"{df['Date'].iloc[fold_val_idx[-1]].date()})")

    fold_preds = {}

    for name in ALL_CANDIDATES:
        if name == "LSTM":
            val_pred = _train_lstm_predict(X_fold_train_sc, y_fold_train, X_fold_val_sc)
            print(f"  Trained the single fixed-seed-42 LSTM on Fold {fold_num}'s training rows, "
                  f"predicted Fold {fold_num}'s validation rows.")
        else:
            candidate_model_fold = clone(phase1_templates[name])
            candidate_model_fold.fit(X_fold_train_sc, y_fold_train)
            val_pred = candidate_model_fold.predict(X_fold_val_sc)
            print(f"  Trained {name} on Fold {fold_num}'s training rows, "
                  f"predicted Fold {fold_num}'s validation rows.")

        fold_preds[name] = val_pred

        fold_pool_positions = np.array([pool_position[i] for i in fold_val_idx])
        oof_predictions[name][fold_pool_positions] = val_pred

        fold_metric_row = _metrics_row(name, y_fold_val, val_pred, prefix="Val")
        fold_metric_row["Fold"] = fold_num
        fold_metric_rows.append(fold_metric_row)

    fold_records.append({
        "fold": fold_num,
        "val_idx": fold_val_idx,
        "y_val": y_fold_val,
        "is_monsoon_val": is_monsoon_fold_val,
        "preds": fold_preds,
    })

fold_metrics_df = pd.DataFrame(fold_metric_rows)
avg_val_diagnostics_df = (
    fold_metrics_df
    .drop(columns=["Fold"])
    .groupby("Model", as_index=False)
    .mean(numeric_only=True)
)
avg_val_diagnostics_ranked = _tie_breaker_rank(
    avg_val_diagnostics_df, "Val_KGE", "Val_NSE", "Val_R2", "Val_MAE", "Val_RMSE"
)

print("\n" + "=" * 90)
print(f"[DIAGNOSTIC ONLY - NOT USED FOR MODEL SELECTION] AVERAGED PER-FOLD VALIDATION "
      f"PERFORMANCE (mean across {len(expanding_window_folds)} folds; "
      "sorted by rounded KGE > rounded NSE > rounded R2 > MAE > RMSE)")
print("=" * 90)
print(avg_val_diagnostics_ranked.round(4).to_string(index=False))
print("\n(This averaged-fold view is retained for inspection only. The official model-selection "
      "ranking below uses POOLED OOF metrics instead - see PART A/B.)")

oof_mask = ~np.isnan(oof_predictions[ALL_CANDIDATES[0]])

print("\n" + "=" * 90)
print("STEP 4 PART 1, PART A: POOLED OOF DATASET & POOLED OOF METRICS (2009-2016)")
print("=" * 90)

pool_dates = df["Date"].values[pool_idx]
pool_years = df["Year"].values[pool_idx]
pool_months = df["Month"].values[pool_idx]

pooled_oof_df = pd.DataFrame({
    "Date": pool_dates[oof_mask],
    "Observed": y_pool[oof_mask],
    "Year": pool_years[oof_mask],
    "Month": pool_months[oof_mask],
    "is_monsoon": is_monsoon_pool[oof_mask],
})
for name in ALL_CANDIDATES:
    pooled_oof_df[name] = oof_predictions[name][oof_mask]

pooled_oof_df = pooled_oof_df.sort_values("Date").reset_index(drop=True)

assert not pooled_oof_df[list(ALL_CANDIDATES)].isnull().to_numpy().any(), (
    "Every pooled OOF row must have exactly one prediction from every candidate model."
)
assert pooled_oof_df["Year"].min() >= 2009 and pooled_oof_df["Year"].max() <= 2016, (
    "pooled_oof_df must contain only 2009-2016 validation observations."
)
assert all(
    pooled_oof_df[pooled_oof_df[name].notna()]["Date"].tolist() == pooled_oof_df["Date"].tolist()
    for name in ALL_CANDIDATES
), "Every candidate model must have OOF predictions on exactly the same set of dates."

print(f"pooled_oof_df shape: {pooled_oof_df.shape} "
      f"(covers {pooled_oof_df['Date'].min().date()} to {pooled_oof_df['Date'].max().date()})")
print(f"Columns: {list(pooled_oof_df.columns)}")
print("Verified: every pooled OOF row has predictions from all "
      f"{len(ALL_CANDIDATES)} candidate models, all models share the same OOF dates, "
      "and only 2009-2016 observations are present.")

y_oof_all = pooled_oof_df["Observed"].values

pooled_metric_rows = [
    _metrics_row(name, y_oof_all, pooled_oof_df[name].values, prefix="OOF")
    for name in ALL_CANDIDATES
]
pooled_metrics_df = pd.DataFrame(pooled_metric_rows)

print("\nPooled OOF metrics for every candidate model:")
print(pooled_metrics_df.round(4).to_string(index=False))

print("\n" + "=" * 90)
print("STEP 4 PART 1, PART B: BEST MODEL SELECTION (POOLED OOF TIE-BREAKER)")
print("=" * 90)

full_val_ranked = _tie_breaker_rank(
    pooled_metrics_df, "OOF_KGE", "OOF_NSE", "OOF_R2", "OOF_MAE", "OOF_RMSE"
)

print("\nPooled OOF ranking:")
print(full_val_ranked.round(4).to_string(index=False))

best_model_name = full_val_ranked["Model"].iloc[0]
best_model_family = MODEL_FAMILIES[best_model_name]
best_kge = full_val_ranked.loc[full_val_ranked["Model"] == best_model_name, "OOF_KGE"].iloc[0]

print(f"\nBest model (official selection criterion, pooled OOF): {best_model_name} "
      f"(family: {best_model_family})")
print(f"Best pooled OOF_KGE: {best_kge:.4f}")

print("\n" + "=" * 90)
print("STEP 4 PART 1, PART C: SECOND MODEL SELECTION (THRESHOLD + FAMILY + POOLED OOF CORRELATION)")
print("=" * 90)

threshold_kge = best_kge - 0.03

print(f"Threshold OOF_KGE (Best - 0.03): {threshold_kge:.4f}")

candidate_pool_df = full_val_ranked[
    (full_val_ranked["OOF_KGE"] >= threshold_kge)
    & (full_val_ranked["Model"] != best_model_name)
    & (full_val_ranked["Model"].map(MODEL_FAMILIES) != best_model_family)
].copy()

if len(candidate_pool_df) > 0:
    candidate_pool_df["Family"] = candidate_pool_df["Model"].map(MODEL_FAMILIES)

    candidate_names_for_corr = [best_model_name] + candidate_pool_df["Model"].tolist()
    oof_df_filtered = pooled_oof_df[candidate_names_for_corr]
    oof_corr_matrix_filtered = oof_df_filtered.corr(method="pearson")

    candidate_pool_df["OOF_Corr_with_Best"] = candidate_pool_df["Model"].apply(
        lambda name: oof_corr_matrix_filtered.loc[best_model_name, name]
    )

    print("\nCandidate models remaining after threshold filtering:")
    print(candidate_pool_df[["Model", "Family", "OOF_KGE", "OOF_Corr_with_Best"]].round(4).to_string(index=False))

    print("\nPearson correlation matrix of pooled OOF predictions (2009-2016):")
    print(oof_corr_matrix_filtered.round(4).to_string())

    if len(candidate_pool_df) == 1:
        second_model_name = candidate_pool_df["Model"].iloc[0]
        second_model_kge = candidate_pool_df["OOF_KGE"].iloc[0]
        second_model_corr = candidate_pool_df["OOF_Corr_with_Best"].iloc[0]
        selection_reason = (
            f"only candidate remaining after threshold filtering (OOF_KGE >= {threshold_kge:.4f}, "
            f"different family from '{best_model_family}') - selected automatically"
        )
    else:
        best_row = candidate_pool_df.loc[candidate_pool_df["OOF_Corr_with_Best"].idxmin()]
        second_model_name = best_row["Model"]
        second_model_kge = best_row["OOF_KGE"]
        second_model_corr = best_row["OOF_Corr_with_Best"]
        selection_reason = (
            f"lowest pooled OOF prediction correlation with {best_model_name} "
            f"(corr = {best_row['OOF_Corr_with_Best']:.4f}) among threshold-filtered, "
            f"different-family candidates"
        )
else:
    oof_corr_matrix_filtered = pd.DataFrame()
    fallback_df = full_val_ranked[
        full_val_ranked["Model"].map(MODEL_FAMILIES) != best_model_family
    ]
    second_model_name = fallback_df["Model"].iloc[0]
    second_model_kge = fallback_df["OOF_KGE"].iloc[0]
    second_model_corr = np.nan
    selection_reason = (
        f"no candidate satisfied the OOF_KGE >= {threshold_kge:.4f} threshold - fell back to the "
        f"highest-ranked model from a different family ('{MODEL_FAMILIES[second_model_name]}') "
        f"using the pooled OOF ranking"
    )

print(f"\nSecond ensemble member selected: {second_model_name} "
      f"(family: {MODEL_FAMILIES[second_model_name]})")
print(f"Reason: {selection_reason}")

selected_model_names = [best_model_name, second_model_name]
print(f"\nSelected ensemble members: {selected_model_names}")

print("\n" + "=" * 90)
print("SAVING STEP 4 PART 1 ARTIFACTS")
print("=" * 90)

pooled_oof_predictions_path = "pooled_OOF_predictions_2009_2016.csv"
pooled_oof_df.to_csv(pooled_oof_predictions_path, index=False)

pooled_oof_metrics_path = "pooled_OOF_model_metrics.csv"
pooled_metrics_df.to_csv(pooled_oof_metrics_path, index=False)

pooled_oof_ranking_path = "pooled_OOF_model_ranking.csv"
full_val_ranked.to_csv(pooled_oof_ranking_path, index=False)

pooled_oof_corr_path = "pooled_OOF_Pearson_correlation.csv"
oof_corr_matrix_filtered.to_csv(pooled_oof_corr_path)

selected_base_models_df = pd.DataFrame([{
    "Best_Model": best_model_name,
    "Best_Model_Family": best_model_family,
    "Best_OOF_KGE": best_kge,
    "Threshold_KGE": threshold_kge,
    "Second_Model": second_model_name,
    "Second_Model_Family": MODEL_FAMILIES[second_model_name],
    "Second_Model_OOF_KGE": second_model_kge,
    "Second_Model_Pearson_Correlation": second_model_corr,
    "Selection_Reason": selection_reason,
}])
selected_base_models_path = "selected_base_models.csv"
selected_base_models_df.to_csv(selected_base_models_path, index=False)

# ===========================================================================
# ==================== STEP 4, PART 2: MULTI-METHOD OOF ENSEMBLE STACKING ====================
# ===========================================================================
print("\n" + "=" * 90)
print("STEP 4 PART 2: MULTI-METHOD OOF ENSEMBLE STACKING")
print("=" * 90)

meta_feature_columns = list(selected_model_names)
model1_name, model2_name = meta_feature_columns

pred1_all = pooled_oof_df[model1_name].values
pred2_all = pooled_oof_df[model2_name].values
y_all_meta = pooled_oof_df["Observed"].values
is_monsoon_meta = pooled_oof_df["is_monsoon"].values

monsoon_mask_meta = is_monsoon_meta == 1
dry_mask_meta = is_monsoon_meta == 0

pred1_monsoon = pred1_all[monsoon_mask_meta]
pred2_monsoon = pred2_all[monsoon_mask_meta]
y_monsoon_meta = y_all_meta[monsoon_mask_meta]

pred1_dry = pred1_all[dry_mask_meta]
pred2_dry = pred2_all[dry_mask_meta]
y_dry_meta = y_all_meta[dry_mask_meta]

# Method 1: Global Ridge Stacking
X_global_ridge = np.column_stack([pred1_all, pred2_all])
global_ridge_model = Ridge(alpha=1.0)
global_ridge_model.fit(X_global_ridge, y_all_meta)
global_ridge_oof_pred = global_ridge_model.predict(X_global_ridge)

# Method 2: Interaction-Ridge Stacking
interaction_feature_names = [
    model1_name, model2_name,
    f"{model1_name}_x_is_monsoon", f"{model2_name}_x_is_monsoon",
    "is_monsoon",
]
X_interaction_ridge = np.column_stack([
    pred1_all, pred2_all,
    pred1_all * is_monsoon_meta, pred2_all * is_monsoon_meta,
    is_monsoon_meta,
])
interaction_ridge_model = Ridge(alpha=1.0)
interaction_ridge_model.fit(X_interaction_ridge, y_all_meta)
interaction_ridge_oof_pred = interaction_ridge_model.predict(X_interaction_ridge)

# Method 3: Season-Specific Constrained-Weight Ensemble (SLSQP)
weight_bounds = [(0.0, 1.0), (0.0, 1.0)]
weight_sum_constraint = {"type": "eq", "fun": lambda w: np.sum(w) - 1.0}
initial_weights = np.array([0.5, 0.5])


def _monsoon_objective(w, p1, p2, y_true):
    blend = w[0] * p1 + w[1] * p2
    return -kge(y_true, blend)


def _dry_objective(w, p1, p2, y_true):
    blend = w[0] * p1 + w[1] * p2
    return mean_absolute_error(y_true, blend)


monsoon_result = minimize(
    _monsoon_objective, initial_weights,
    args=(pred1_monsoon, pred2_monsoon, y_monsoon_meta),
    method="SLSQP", bounds=weight_bounds, constraints=[weight_sum_constraint],
)
monsoon_weights = monsoon_result.x

dry_result = minimize(
    _dry_objective, initial_weights,
    args=(pred1_dry, pred2_dry, y_dry_meta),
    method="SLSQP", bounds=weight_bounds, constraints=[weight_sum_constraint],
)
dry_weights = dry_result.x

season_specific_weights_df = pd.DataFrame({
    "Base_Model": meta_feature_columns,
    "Monsoon_Weight": monsoon_weights,
    "Dry_Weight": dry_weights,
})

season_specific_oof_pred = np.zeros(len(y_all_meta), dtype=float)
season_specific_oof_pred[monsoon_mask_meta] = (
    monsoon_weights[0] * pred1_monsoon + monsoon_weights[1] * pred2_monsoon
)
season_specific_oof_pred[dry_mask_meta] = (
    dry_weights[0] * pred1_dry + dry_weights[1] * pred2_dry
)

ensemble_oof_predictions_df = pd.DataFrame({
    "Date": pooled_oof_df["Date"].values,
    "Observed": y_all_meta,
    "is_monsoon": is_monsoon_meta,
    model1_name: pred1_all,
    model2_name: pred2_all,
    "Global_Ridge": global_ridge_oof_pred,
    "Interaction_Ridge": interaction_ridge_oof_pred,
    "Season_Specific_Constrained_Weight": season_specific_oof_pred,
}).sort_values("Date").reset_index(drop=True)

ensemble_oof_performance_rows = [
    _metrics_row(model1_name, y_all_meta, pred1_all, prefix="OOF"),
    _metrics_row(model2_name, y_all_meta, pred2_all, prefix="OOF"),
    _metrics_row("Global_Ridge", y_all_meta, global_ridge_oof_pred, prefix="OOF"),
    _metrics_row("Interaction_Ridge", y_all_meta, interaction_ridge_oof_pred, prefix="OOF"),
    _metrics_row("Season_Specific_Constrained_Weight", y_all_meta, season_specific_oof_pred, prefix="OOF"),
]
ensemble_oof_performance_ranked = pd.DataFrame(ensemble_oof_performance_rows).sort_values(
    "OOF_KGE", ascending=False
).reset_index(drop=True)

print(ensemble_oof_performance_ranked.round(4).to_string(index=False))

ensemble_oof_predictions_df.to_csv("ensemble_oof_predictions.csv", index=False)
ensemble_oof_performance_ranked.to_csv("ensemble_oof_performance.csv", index=False)

# ===========================================================================
# ==================== STEP 5: FINAL REFIT AND TEST SET EVALUATION ====================
# ===========================================================================
os.makedirs("results", exist_ok=True)

print("\n" + "=" * 90)
print("STEP 5 PART A: FULL-POOL REFIT (2003-2016 POOL; TEST SET STILL UNTOUCHED)")
print("=" * 90)

scaler_pool = StandardScaler()
X_pool_sc = scaler_pool.fit_transform(X_pool)
X_test_sc = scaler_pool.transform(X_test)

phase2_templates = build_models()
test_preds = {}

for name in selected_model_names:
    if name == "LSTM":
        test_preds[name] = _train_lstm_predict(X_pool_sc, y_pool, X_test_sc)
        print(f"Refit the single fixed-seed-42 LSTM on the full 2003-2016 pool.")
    else:
        final_model = clone(phase2_templates[name])
        final_model.fit(X_pool_sc, y_pool)
        test_preds[name] = final_model.predict(X_test_sc)
        print(f"Refit {name} on the full 2003-2016 pool.")

test_pred1 = test_preds[model1_name]
test_pred2 = test_preds[model2_name]
X_test_meta_global = np.column_stack([test_pred1, test_pred2])

# Global Ridge inference
global_ridge_test_pred = global_ridge_model.predict(X_test_meta_global)

# Interaction Ridge inference
X_test_meta_interaction = np.column_stack([
    test_pred1, test_pred2,
    test_pred1 * is_monsoon_test, test_pred2 * is_monsoon_test,
    is_monsoon_test,
])
interaction_ridge_test_pred = interaction_ridge_model.predict(X_test_meta_interaction)

# Season-Specific Constrained-Weight inference
monsoon_mask_test = is_monsoon_test == 1
dry_mask_test = is_monsoon_test == 0

season_specific_test_pred = np.zeros(len(y_test), dtype=float)
season_specific_test_pred[monsoon_mask_test] = (
    monsoon_weights[0] * test_pred1[monsoon_mask_test] + monsoon_weights[1] * test_pred2[monsoon_mask_test]
)
season_specific_test_pred[dry_mask_test] = (
    dry_weights[0] * test_pred1[dry_mask_test] + dry_weights[1] * test_pred2[dry_mask_test]
)

print("\n" + "=" * 90)
print("STEP 5 PART E: FINAL TEST-SET PERFORMANCE - FIRST TEST-SET LOOK")
print("=" * 90)

final_rows = [
    _metrics_row(best_model_name, y_test, test_preds[best_model_name], prefix="Test"),
    _metrics_row(second_model_name, y_test, test_preds[second_model_name], prefix="Test"),
    _metrics_row("Global Ridge Stacking Ensemble", y_test, global_ridge_test_pred, prefix="Test"),
    _metrics_row("Interaction Ridge Stacking Ensemble", y_test, interaction_ridge_test_pred, prefix="Test"),
    _metrics_row("Season-Specific Constrained-Weight Ensemble", y_test, season_specific_test_pred, prefix="Test"),
]
final_summary_df = pd.DataFrame(final_rows)
final_summary_sorted = final_summary_df.sort_values("Test_KGE", ascending=False).reset_index(drop=True)

print(final_summary_sorted.round(4).to_string(index=False))

final_summary_sorted.to_csv("results/final_test_performance.csv", index=False)

test_dates = df["Date"].values[test_idx]
test_predictions_all_models_df = pd.DataFrame({
    "Date": test_dates,
    "Observed_Streamflow": y_test,
    "is_monsoon": is_monsoon_test,
    "Best_Model_Predicted": test_preds[best_model_name],
    "Second_Model_Predicted": test_preds[second_model_name],
    "Global_Ridge_Stacking_Predicted": global_ridge_test_pred,
    "Interaction_Ridge_Stacking_Predicted": interaction_ridge_test_pred,
    "Season_Specific_Constrained_Weight_Predicted": season_specific_test_pred,
}).sort_values("Date").reset_index(drop=True)
test_predictions_all_models_df.to_csv("results/test_predictions_all_models.csv", index=False)

season_specific_weights_df.to_csv("results/season_specific_weights.csv", index=False)

print("\nDone. See the 'results/' folder for all outputs.")